version: "3.8"
services:
  strfry:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    volumes:
      - strfry_data:/app/strfry-db
    expose:
      - "7777"
    networks: [dokploy-network]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strfry.rule=Host(`${RELAY_HOST}`)"
      - "traefik.http.routers.strfry.entrypoints=websecure"
      - "traefik.http.routers.strfry.tls=true"
      - "traefik.http.services.strfry.loadbalancer.server.port=7777"
networks:
  dokploy-network:
    external: true
volumes:
  strfry_data:
