services:
  strfry:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    volumes:
      - strfry_data:/app/strfry-db
      - ./strfry/strfry.conf:/tmp/strfry.conf:ro # bind config to temp location
    entrypoint: ["/bin/sh", "-c"]
    command: ["cp /tmp/strfry.conf /app/strfry.conf && /app/strfry relay"]
    expose:
      - "7777"
    networks: [dokploy-network]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strfry.rule=Host(`${RELAY_HOST}`)"
      - "traefik.http.routers.strfry.entrypoints=websecure"
      - "traefik.http.routers.strfry.tls=true"
      - "traefik.http.services.strfry.loadbalancer.server.port=7777"
networks:
  dokploy-network:
    external: true
volumes:
  strfry_data:
